# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Unity Windows Agents
  demands: JDK

steps:
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Android'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'

- powershell: |
   Write-Host "##vso[task.setvariable variable=Android_Home;]C:\AndroidSDK"
  displayName: 'PowerShell Script'

- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) $(Build.BinariesDirectory)/*.apk'
  inputs:
    apkFiles: '$(Build.BinariesDirectory)/*.apk'
    apksignerKeystoreFile: '9e0392c3-92c0-42db-9201-79c730159c78'
    apksignerKeystorePassword: d0bqZ971
    apksignerKeystoreAlias: 'my_key_alias'
    apksignerKeyPassword: yT93zfT

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AppCenterDistribute@3
  displayName: 'Deploy $(Build.ArtifactStagingDirectory)/drop.apk to Visual Studio App Center'
  inputs:
    serverEndpoint: VSAP
    appSlug: maksIV975/TestApp
    appFile: '$(Build.ArtifactStagingDirectory)/drop.apk'
    symbolsOption: Android
    releaseNotesInput: 'First release'
    isSilent: false
